services:
  - type: web
    name: aaa-github-auto-ai-advisory
    env: python
    plan: free
    rootDir: .
    buildCommand: bash builder.sh
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
